# 1.4.4 Smoothing Images

## Kernel Convolution

In [18]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [19]:
l=1
kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]],np.float32)

In [20]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  4., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [21]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [22]:
img

array([[8, 6, 9, 9, 1, 6, 7, 3, 9, 9, 4, 3],
       [1, 2, 2, 4, 9, 4, 7, 6, 2, 7, 8, 2],
       [2, 8, 1, 5, 0, 2, 2, 1, 1, 5, 1, 1],
       [7, 0, 0, 7, 5, 6, 9, 1, 2, 4, 9, 9],
       [7, 0, 2, 5, 6, 3, 5, 6, 3, 0, 7, 7],
       [7, 4, 5, 6, 7, 3, 6, 5, 7, 9, 1, 8],
       [6, 9, 8, 2, 3, 0, 3, 7, 9, 1, 3, 8],
       [0, 4, 7, 4, 1, 0, 7, 4, 3, 7, 3, 1],
       [1, 7, 9, 5, 9, 5, 5, 2, 0, 0, 3, 5],
       [6, 9, 6, 6, 8, 9, 5, 7, 5, 0, 8, 4],
       [1, 4, 3, 9, 9, 0, 2, 1, 6, 6, 0, 1],
       [5, 9, 9, 9, 1, 0, 3, 6, 2, 4, 6, 1]])

In [23]:
h,w=img.shape

In [24]:
print(h,w)

12 12


In [25]:
#[*range(-2,3)]

In [26]:
dst = np.zeros((h,w),np.int)

<ipython-input-26-6137fcb8b1c2>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dst = np.zeros((h,w),np.int)


In [27]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [28]:
img

array([[8, 6, 9, 9, 1, 6, 7, 3, 9, 9, 4, 3],
       [1, 2, 2, 4, 9, 4, 7, 6, 2, 7, 8, 2],
       [2, 8, 1, 5, 0, 2, 2, 1, 1, 5, 1, 1],
       [7, 0, 0, 7, 5, 6, 9, 1, 2, 4, 9, 9],
       [7, 0, 2, 5, 6, 3, 5, 6, 3, 0, 7, 7],
       [7, 4, 5, 6, 7, 3, 6, 5, 7, 9, 1, 8],
       [6, 9, 8, 2, 3, 0, 3, 7, 9, 1, 3, 8],
       [0, 4, 7, 4, 1, 0, 7, 4, 3, 7, 3, 1],
       [1, 7, 9, 5, 9, 5, 5, 2, 0, 0, 3, 5],
       [6, 9, 6, 6, 8, 9, 5, 7, 5, 0, 8, 4],
       [1, 4, 3, 9, 9, 0, 2, 1, 6, 6, 0, 1],
       [5, 9, 9, 9, 1, 0, 3, 6, 2, 4, 6, 1]])

In [29]:
dst

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,  -9,  -8,  -9,  27,  -8,   9,  11, -15,   4,  18,   0],
       [  0,  27, -11,   8, -21,  -4, -11,  -6,  -6,   7, -19,   0],
       [  0, -15, -10,  13,   1,   5,  22, -14,  -1,   0,  15,   0],
       [  0, -13,  -2,  -1,   4,  -8,  -4,  10,  -3, -23,  11,   0],
       [  0,  -5,   0,   5,  10,  -4,   8,  -6,   2,  27, -23,   0],
       [  0,  14,   9, -13,   2,  -9,  -8,   7,  18, -24,  -1,   0],
       [  0,  -7,   3,   1, -12, -13,  16,  -3,  -8,  21,  -2,   0],
       [  0,   5,  11,  -8,  17,  -3,   1,  -8, -10, -10,  -4,   0],
       [  0,  13,  -3,  -4,  -1,  18,  -3,  15,   7, -19,  25,   0],
       [  0,  -6, -16,   9,  18, -20,  -1, -17,  10,  14, -21,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [35]:
img = cv2.imread('lena.png', 0)

In [36]:
l=1
kernel = np.array([[0,-1,0],[-1,5,-1],[0,-1,0]],np.float32)

In [37]:
h,w=img.shape

In [38]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [39]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [40]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()